name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Install dependencies
        run: |
          python -m virtualenv helloworld
          source helloworld/bin/activate
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: |
          source helloworld/bin/activate
          python test_hello_world.py